version: 1.0.{build}
build_cloud: WIN-LKR467JS4GL
image: Windows
platform:
- x86
- x64
- ARM64
configuration:
- Release
test: off
skip_commits:
  files:
    - assets/*
    - '**/*.md'
    - '**/*.json'
install:
- cmd: git submodule -q update --init
- cmd: vcpkg integrate install
- cmd: vcpkg update
- ps: Setup-VS2022 $env:PLATFORM
before_build:
- cmd: nuget restore
- cmd: vpatch.exe --stamp-version "%APPVEYOR_BUILD_VERSION%" --target-file ".\src\vīcĭus.rc" --resource.file-version --resource.product-version
build:
  project: $(APPVEYOR_BUILD_FOLDER)\vīcĭus.sln
artifacts:
- path: bin\**\*.exe
  name: Updater
deploy:
- provider: Environment
  name: BUILDBOT
  on:
    appveyor_repo_tag: true
